### PR TITLE
Use proper service name for theme context

### PR DESCRIPTION
**Pull request by ahilles107**

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Actually, I think we should rename it to ``sylius.context.theme`` in code. :) /cc @pamil

**Comment by ahilles107** [comment]
Btw. Looks like whole themes chapter needs some review - lot's of stuff is missing (for example mandatory config part - without it Bundle don't see any themes) or already refactored and invalid in documentation (like repository function name in example listener). I can help with that but would be nice to hear about some roadmap for this bundle - to not write documentation for parts witch will be refactored soon.

**Comment by ahilles107** [comment]
any decisions?

**Comment by pjedrzejewski** [comment]
@ahilles107 This is a fairly new bundle, so there will be a lot of changes, we will do our best to keep the doc up-to-date. In latest PR https://github.com/Sylius/Sylius/pull/4268 this is renamed IIRC.

**Pull request closed without merging**
