### PR TITLE
Update inventory configuration

### PR DESCRIPTION
**Pull request by umpirsky**

### CODE REVIEW

**Comment by aRn0D** [comment]
Thanks Sir !

**Comment by pjedrzejewski** [comment]
StackOverflow. :dancer:  Thanks Sasha! :+1:

**Comment by umpirsky** [comment]
@pjedrzejewski Hah, yes! :smile_cat:

**Comment by JacquesDufour** [comment]
After correct that config error,  I get this: 
Fatal error: Class 'Sylius\Bundle\InventoryBundle\Entity\InventoryUnit' not found in ...\App\AppBundle\Entity\InventoryUnit.php on line 19

**Comment by umpirsky** [comment]
@JacquesDufour Can you gist us `App\AppBundle\Entity\InventoryUnit.php` please?

**Comment by pjedrzejewski** [comment]
It is in "Model" namespace, not "Entity". @JacquesDufour

**Comment by pjedrzejewski** [comment]
Class name is ``Sylius\Component\Inventory\Model\InventoryUnit``.

**Comment by JacquesDufour** [comment]
Okay. Thanks!

**Pull request merged**
