### PR TITLE
[ResourceBundle] replace contoller and repository classes by DI-param…

### PR DESCRIPTION
**Pull request by Strontium-90**
Doc for this PR https://github.com/Sylius/Sylius/pull/2808

### CODE REVIEW

**Comment by aRn0D** [comment]
@Strontium-90 you're wrong because those parameters only exist after the container is built (not before)

**Comment by Strontium-90** [comment]
@aRn0D, its true, only if ResourceBundle was registered after concrete resource budles. If its was registered first, its ok. But now it is not.

**Comment by Strontium-90** [comment]
Should we avoid using `Sylius\Bundle\ResourceBundle\Controller\ResourceController` in concrete resource configuration and let AbstractDatabaseDriver using `sylius.controller.class` if it is not defined?

**Comment by Strontium-90** [comment]
@aRn0D, so what about register `ResourceBundle` before all other dependent bundles?

**Comment by aRn0D** [comment]
@Strontium-90 Impossible, all bundle configurations must be parsed to rewrite the doctrine mapping.

**Comment by Strontium-90** [comment]
@aRn0D, is it better rewrite mapping in CompilerPass?

**Comment by aRn0D** [comment]
We are going to do that: https://github.com/Sylius/Sylius/issues/2622.

**Pull request closed without merging**
