### PR TITLE
Update VariantGenerator documentation to use Set Builders

### PR DESCRIPTION
**Pull request by adamelso**
Q  | A
----|----
Doc fix? | no
New docs? | yes
Fixed tickets | 

Related PR pending on Sylius.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@adamelso Could you rebase? Thank you! :+1:

**Comment by adamelso** [comment]
@pjedrzejewski thanks, done :+1:

**Comment by adamelso** [comment]
@pjedrzejewski ping :)

**Comment by pjedrzejewski** [comment]
:+1:

**Pull request merged**
